safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    /
url: http://local.stefano.oldeman.github.com:400

source:      .
destination: ./_site
plugins:     ./_plugins

app:
    media_path: /assets
    minified: ""
    version: 0.1
