safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    /
url: http://local.stefano.oldeman.github.com:400

source:      .
destination: ./_site

app:
    media_path: /assets
    minified: ".min"
    version: 0.2
